spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
